apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: bachend-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exploreworld
  template:
    metadata:
      labels:
        app: exploreworld
    spec:
      containers:
      - name: backend-container
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
